[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "flask-cors>=5.0.1",
    "flask>=3.1.0",
    "requests>=2.32.3",
]
